### PR TITLE
Modify theme toggle switch

### PR DESCRIPTION
**Pull request by Hrishabh5**
# Description
Modified the theme toggler switch.

Fixes # (issue no.) 
Theme toggler was not looking good

### CODE REVIEW

**Comment by Hrishabh5** [comment]
Screenshot 2021-10-05 at 1 29 57 AM


Screenshot 2021-10-05 at 1 30 29 AM


This is how the toggler looks now.

**Comment by Hrishabh5** [comment]
https://user-images.githubusercontent.com/71200145/136101631-5561b14a-dd3c-4f34-a0c0-380d24566960.mov

Now it's fine.

**Comment by samz5320** [comment]
yup looks cool.

**Comment by Hrishabh5** [comment]
> yup looks cool.

Thank you 😊

**Comment by honeykpatel** [comment]
@Hrishabh5  DUDE, this looks great! 😍

**Pull request merged**
