### PR TITLE
Add dataset of Cat and Dog

### PR DESCRIPTION
**Pull request by ramya-neelakantan**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

### CODE REVIEW

**Comment by samz5320** [comment]
could you link them in the index.html too pls?

**Comment by ramya-neelakantan** [comment]
> could you link them in the index.html too pls?

Done. Can you see my pull request for the same?

**Comment by ramya-neelakantan** [comment]
> > could you link them in the index.html too pls?
> 
> Done. Can you see my pull request for the same?

Please let me know if any more changes have to be done!

**Review by samz5320 — APPROVED** [review]

**Comment by samz5320** [comment]
can u update ur repo and send PR again pls. u hvnt added color coding.

**Comment by ramya-neelakantan** [comment]
> can u update ur repo and send PR again pls. u hvnt added color coding.
What is the color coding that you require?

**Comment by samz5320** [comment]
U can put it as beginners for now. we can change it in the future if needed.

**Comment by ramya-neelakantan** [comment]
> U can put it as beginners for now. we can change it in the future if needed.

Created a new pull request. Please check if it is ok now..

**Pull request merged**
