### PR TITLE
Add Customer Service Personality Dataset

### LINKED ISSUE #1: add datasets
Add file in datasets folder and link it in index.html

### PR DESCRIPTION
**Pull request by cloudy3**
# Description

Added Customer Service Personality Dataset for Hacktoberfest.

Fixes #1  (issue no.) 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by samz5320** [comment]
Your dataset and Name gave to ur card arent similar or give the same meaning. can u recheck names?

**Comment by cloudy3** [comment]
Yup don't worry it is referring to the correct dataset. Somehow it is named differently when I downloaded it, but rest assured I have checked the dataset.

**Comment by samz5320** [comment]
I meant the title you have given to the dataset and the actual name of the dataset

**Comment by cloudy3** [comment]
Okay I have renamed my dataset!

**Review by samz5320 — APPROVED** [review]

**Pull request merged**
