### PR TITLE
Modified Readme

### LINKED ISSUE #6: Prettify Readme.md

### PR DESCRIPTION
**Pull request by sudeepshukla930**
# Description

I had modified the Readme to give a new look to it

Fixes #6  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updated the Readme

 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS
Screenshot (653)
Screenshot (654)

Screenshot (655)](https://user-images.githubusercontent.com/59015510/135730108-609cafc3-9a63-4123-9518-30cf298dcc05.png)
githubusercontent.com/59015510/135730105-10fd1c38-aefb-43cf-b476-f68ff284266e.png)

### CODE REVIEW

**Comment by samz5320** [comment]
It looks crazy nice one!. but can u update ur repo using git pull to get the latest changes and add ur changes pls?
also save ur changes .cause when u git pull ur changes will be over written.

**Comment by sudeepshukla930** [comment]
Hey @samz5320 , I have fetched and pull all the changes  in the repo
Can you please merge it 
Thankyou

**Comment by samz5320** [comment]
can u put ur images in the images folder pls?

**Comment by sudeepshukla930** [comment]
Hey @samz5320 , I have added images into the images folder.
Thanks

**Review by samz5320 — APPROVED** [review]

**Pull request merged**
