### PR TITLE
color-coded datasets

### PR DESCRIPTION
**Pull request by RohanTheProgrammer**
you can change their category just by changing their class as `'beginner'`, `'inter'` or `'adv'`.

### CODE REVIEW

**Comment by RohanTheProgrammer** [comment]
#13

**Review by samz5320 — CHANGES_REQUESTED** [review]
please pull and update ur repo before pushing.

also can you attach final ss with ur pull req pls. thank you

**Comment by RohanTheProgrammer** [comment]
Screenshot (36)
Screenshot (37)

**Comment by RohanTheProgrammer** [comment]
@samz5320  Is it good now

**Review by samz5320 — APPROVED** [review]

**Pull request merged**
