### PR TITLE
Replaced copy button to icon

### LINKED ISSUE #51: Copy icon instead of the button
It seems like a copy icon (as a button) would be better rather than the copy link button.

### PR DESCRIPTION
**Pull request by amitmaindola**
# Replaced the copy button with the icon

## Fixes #51  
dark-mode-1
light-mode-1

# Explain the Testing instructions

### CODE REVIEW

**Comment by amitmaindola** [comment]
Please accept the Pull Request, so that I can create new pull requests.

**Comment by samz5320** [comment]
can u try the download icon as it is? also try some colors for the copy link icon pls.

**Comment by amitmaindola** [comment]
Ok sure I'll do that.

**Comment by samz5320** [comment]
It will take some time to accept ur pr cause there are a lot of UI and functional changes suggested by contributors.
I will have to review and test each change.

**Comment by amitmaindola** [comment]
## I have added a downloaded copy.svg  file for copy icon ( which was using font-awesome cdjns before) and also have changed the **color-theme** of icons to make the theme of both **download** and **copy** icons same.

Below are the two screenshot of dark theme and light theme.
NOTE : On hover the color theme of buttons become as other one before having


## Light Theme
light-mode-2
## Dark theme
dark-mode-2
###  Also, Please let me know that would I have to create a new pull request or you are able to fetch my commits through this one.

### And the last point is that you can tell me the colors to use on buttons if you feel that will look better ( Although we can do that easily even at a later step)

**Comment by samz5320** [comment]
I can merge this Pr only.  there is a lot of blue XD.

**Comment by amitmaindola** [comment]
I am not able to create two simultaneous pull requests at the same repo. Now, what should I do?

**Comment by amitmaindola** [comment]
It is showing me that all commits will be automatically merged.

**Comment by amitmaindola** [comment]
@samz5320  Actually this is my first pull req for hacktoberfest, XD.

**Comment by amitmaindola** [comment]
Waiting to see hacktoberfest-accepted tag :')

**Comment by amitmaindola** [comment]
@samz5320   This PR was showing **3 file conflicts found**, actually the fact is that after adding each dataset in the website one conflict will be created each time as the contributors working on this repository are still using the old copy button HTML.
And It will be more and more difficult to solve the conflicts as more and more datasets are introduced.

This time I have solved all the conflicts manually and there is **No conflict** right now so In my opinion you should merge this  PR before you go for the PR's for adding datasets.

**Comment by samz5320** [comment]
The problem is others are working on making "Copy" to "Copied" . and you have added an SVG icon.

**Comment by amitmaindola** [comment]
## @samz5320  Ohh got it!
### actually what I was thinking is that to make this like that one icon that GitHub uses (Image Attached).

image

### Actually if you think that merging this PR is not possible then kindly let me know I will close this PR and will work on other issues in your repo. 😄

**Comment by amitmaindola** [comment]
Meanwhile one more conflict encountered 😅

**Comment by amitmaindola** [comment]
Let me know that should I keep removing the conflicts or close this PR

**Comment by samz5320** [comment]
Yup close this PR. pls u can push once u decide on the design

**Pull request closed without merging**
