### PR TITLE
Added Three Datasets 

### PR DESCRIPTION
**Pull request by codewithgulam**
## **Description** 
1) Added Three more datasets.
2) Updated required changes in Index.htm when adding new datasets.

### CODE REVIEW

**Comment by codewithgulam** [comment]
@samz5320 
Sir please review my PR & merge if it is good.

**Comment by samz5320** [comment]
Can you please change the name of Production od agriculture Dataset in the index.html file as there would be confusing between datasets

**Comment by codewithgulam** [comment]
@samz5320 Sir I have changed that please check it.

**Review by samz5320 — APPROVED** [review]

**Comment by samz5320** [comment]
Can you check if u made any changes to Indian cities  dataset pls ?

**Comment by codewithgulam** [comment]
I've only changed the name when you said.

**Pull request merged**
