### PR TITLE
Bug Fixed copy button copies to clipboard.

### PR DESCRIPTION
**Pull request by RohanTheProgrammer**
# Description

Before the copy button was not working. I fixed the issue with the copy button, now it can copy the dataset link to the clipboard. 

Fixes # (issue no.) 
#11 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
# ATTACH SCREEN-SHOTS

### CODE REVIEW

**Comment by RohanTheProgrammer** [comment]
#11 
@samz5320 Tell me if there is any problem

**Comment by samz5320** [comment]
conflict with script.js 
kindly pull for new changes and try again.

**Comment by RohanTheProgrammer** [comment]
@samz5320  conflicts resolved.

**Comment by samz5320** [comment]
> @samz5320 conflicts resolved.


cant see any datasets. can u confirm with ur ss pls?

**Comment by RohanTheProgrammer** [comment]
but I can't see any dataset in your repo `samz5320/Data4ALL` also

**Comment by samz5320** [comment]
i hv 4 datasets in my repository.

**Comment by samz5320** [comment]
I can see in ur branch also u hv datasets.

**Comment by RohanTheProgrammer** [comment]
let me look it.
Wait for some time

**Comment by RohanTheProgrammer** [comment]
I  am closing this and opened another PR which is working perfectly (I think)
#36

**Pull request closed without merging**
