### PR TITLE
Add filters to the database

### PR DESCRIPTION
**Pull request by honeykpatel**
# Description

Added an all function and added a class to cards (beginner-db, intermediate-db and advanced-db) that filters out Datasets when clicked on respected category. 
**PFA : THE SCREENSHOTS**

Fixes # (issue no.) 
https://github.com/samz5320/Data4ALL/issues/2

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Added functionality that filters datasets on clicking the category
- [x] Also added one more database(intermediate) to check the feature

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

image

And after clicking on beginner it will be like : 

image

### CODE REVIEW

**Comment by samz5320** [comment]
have u checked it for responsive navbar too?

**Comment by honeykpatel** [comment]
> have u checked it for responsive navbar too?

Umm no, i haven't touched navbar..

**Review by samz5320 — APPROVED** [review]

**Comment by samz5320** [comment]
Works great.tq

**Comment by honeykpatel** [comment]
Yay, btw now others will have to add another class like beginner-db with card, so I think we should create a guideline in readme of adding Dataset, what say shall I create a new issue for the same?

**Comment by samz5320** [comment]
Yup create an issue.

**Pull request merged**
