### PR TITLE
Added three datasets and update index.html, README.md, and contribute.md

### PR DESCRIPTION
**Pull request by Mr-vabs**
## Added two new datasets
FDI in India and heart disease

## Updated Readme.md
Added info what is dataset and CSV files

## Updated Contribute.md
Added info of contribution and precautions.

### CODE REVIEW

**Review by Mr-vabs — COMMENTED** [review]
It's working fine , I've tested it. New dataset is displaying on index.html as well as its downloadable as like as other  project's other datasets.

**Comment by Mr-vabs** [comment]
@samz5320
Hello sir 👋 , 
Kindly look into my PR and let me know if I've done everything properly and if there's anything to improve or change please inform me.

**Comment by samz5320** [comment]
startup funding dataset already added.

**Comment by Mr-vabs** [comment]
@samz5320 
Yes sir , I get to know that after I had made my PR. however both are in different format but I'll remove it.

**Comment by Mr-vabs** [comment]
@samz5320 sir as it should be done , I've removed my "startup_funding.csv" and it's html from index.html as well. Is there anything more to remove / update sir ?

**Comment by samz5320** [comment]
> @samz5320 sir as it should be done , I've removed my "startup_funding.csv" and it's html from index.html as well. Is there anything more to remove / update sir ?

Looks good :)

**Comment by Mr-vabs** [comment]
@samz5320 
It's ready to be merge sir ?

**Review by samz5320 — APPROVED** [review]

**Pull request merged**
