### PR TITLE
fixed 'copied' notification after copy is clicked

### PR DESCRIPTION
**Pull request by coder483**

### CODE REVIEW

**Comment by samz5320** [comment]
Looks good. can u update and repo and push please.

**Comment by coder483** [comment]
i updated the repo already

**Comment by coder483** [comment]
can u merge it now

**Comment by samz5320** [comment]
repos not updates u can see ur preview in the netlify link

**Comment by coder483** [comment]
ya because u didnt add my code

**Comment by coder483** [comment]
i also resolve the conflict

**Review by samz5320 — APPROVED** [review]

**Review by samz5320 — APPROVED** [review]

**Pull request merged**
