### PR TITLE
Added the main attraction(icon) to your web page and the idea of project is great because this is the first time i am seeing these datasets

### PR DESCRIPTION
**Pull request by rohitkothapalli**
# Description

The main thing is i added an icon to your webpage. I loved the idea of your project verymuch as this is the first time i am seeing datasets.
Type of change 
A change in Head of webpage and an enhancement

image

### CODE REVIEW

**Comment by samz5320** [comment]
Html files is messed up. u can check the review

**Review by rohitkothapalli — COMMENTED** [review]
Bruh Pls Merge as a part of hactoberfest2021

**Comment by rohitkothapalli** [comment]
wait let me solve coz every one is creating prs and doing a mess in the code i will resolve @samz5320

**Comment by rohitkothapalli** [comment]
done bruh pls check no need of deleting the pr conflicts solved @samz5320

**Comment by samz5320** [comment]
use netlify links to check ur preview. there are still bugs.
check the deploy preview ready.

**Comment by rohitkothapalli** [comment]
okay sure

**Pull request closed without merging**
