### PR TITLE
Added new Parkinson Dataset and edited the html file

### PR DESCRIPTION
**Pull request by Ollie-beep-bop**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS

### CODE REVIEW

**Comment by Ollie-beep-bop** [comment]
I added a dataset So will that count for Hactoberfest 2021? I am sorry I am new to this.

**Review by samz5320 — APPROVED** [review]

**Comment by samz5320** [comment]
Yup . it will.

**Comment by Ollie-beep-bop** [comment]
Thank you, for the reply! Can the tag be added so that it gets accepted as a PR? because for me its showing 
image

**Comment by samz5320** [comment]
I have added the tag hacktober-accepted.

**Pull request merged**
